### ISSUE TITLE
NameError: name 'primitive_matrix' is not defined

### ISSUE THREAD

**Issue by sooran121** [yuzie007/upho#3]
Dear all,

I've been testing an example in "tests/L21_Cu3Au"

I encountered an error when I type "upho_weights band.conf"
---------------------------------------
    elif primitive_matrix is not None:
NameError: name 'primitive_matrix' is not defined 
---------------------------------------
I checked the previous issue https://github.com/yuzie007/upho/issues/2
and changed the line 52 in api_unfolding.py from "elif primitive_matrix is not None:" to "elif primitive_matrix_ideal is not None:"

It solved the problem.

May I ask the correction is right?
Thank you.

Best regards,
Sooran Kim

**Comment by yuzie007** [comment]
Thank you so much for letting me know the bug of the variable name. I think the correction is right. For the planned latest version (v0.6.2) I will fix the issue.
